### ISSUE TITLE
Error on running under MODX 2.7.3

### ISSUE THREAD

**Issue by shepaldo** [modmore/BigBrother#34]
Not sure this is still working with MODX 2.7+ ?
From MODX error log:
[2020-07-14 12:44:10] (ERROR in modProcessor::run @ /home/sites/6a/4/4c8bd13241/public_html/core/model/modx/modprocessor.class.php : 177) Flat file processor support, used for action authenticate/verifyPrerequisite with path /home/sites/6a/4/4c8bd13241/public_html/core/components/bigbrother/processors/mgr/authenticate/verifyprerequisite.php, is deprecated since version 2.7.0
![Screenshot 2020-07-14 at 12 45 28](https://user-images.githubusercontent.com/718308/87431693-eabeb600-c5de-11ea-8cf0-7f99243b9853.jpg)

**Comment by Mark-H** [comment]
That deprecation message does not cause any problems. That just needs to be addressed for it to work on MODX 3.

It sounds like it's failing to verify simplexml and curl on your server. Please check those are installed.

**Comment by Mark-H** [comment]
And honestly, I released an update yesterday. How can you see an update one day before and suggest it doesn't work on the current version of MODX?!

**Comment by shepaldo** [comment]
Sorry, put it down to my excitement. Your efforts are very much appreciated.

**Comment by Mark-H** [comment]
Sorry for snapping - had a really frustrating day and that comment just hit me the wrong way while I was already bashing my head in.

It's possible your issue was caused by the modAction reference in 69c6c46b5fa4069ca9a284d5a191e59363a91841. If you haven't been able of getting it authorized and you do have simplexml and curl on the server (check your phpinfo under manage > reports > system info), that probably threw a fatal error and you'll have more luck with 1.4.1. I'll push that release in the next few days as I'm currently working with Google's review team to get the oAuth flow approved and want to bundle any more tweaks they demand in the same release.

**Comment by shepaldo** [comment]
No problem at all! We are all having a hard time this week it seems - good
luck with Google!

KR,

Andy


[image: photo]
Andy Sheppard
IT Consultant at Vuvumo

<http://facebook.com/vuvumo> <http://uk.linkedin.com/in/vuvumo>
<http://twitter.com/andysheppard> <http://500px.com/andysheppard>
Phone  +44 7703 184024  <+44 7703 184024>
Email  andy@vuvumo.com  <andy@vuvumo.com>
Website  www.vuvumo.com  <http://www.vuvumo.com>
  <https://zoom.us/j/6456548305> <https://zoom.us/j/6456548305> Meet me on
Zoom <https://zoom.us/j/6456548305>   <https://zoom.us/j/6456548305>

IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
Please consider the environment before printing this e-mail!
